int i = 123; double d;
d = i;
Console.WriteLine(d);
short s = 100;
int j;
j = s;
Console.WriteLine(j);
char c = 'A';
int k;
k = c;
Console.WriteLine(c);
Console.WriteLine(k);
int ascciCode = 65;
char ch = (char)ascciCode;
Console.WriteLine(ch);
float f = 3.14f;
int a;
a = (int)f;
Console.WriteLine(a);