int age = 2000000000;
Console.WriteLine(age);
float pi = 3.14e30f;
Console.WriteLine(pi);
double temperature = 36.6e90;
Console.WriteLine(temperature);
char dollar = '$';
Console.WriteLine(dollar);
String name = "Nixware Consulting";
Console.WriteLine(name);